/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as FollowUpsRouteImport } from './routes/follow-ups'
import { Route as IndexRouteImport } from './routes/index'

const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowUpsRoute = FollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/follow-ups': typeof FollowUpsRoute
  '/jobs': typeof JobsRoute
  '/leads': typeof LeadsRoute
  '/quote': typeof QuoteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/follow-ups': typeof FollowUpsRoute
  '/jobs': typeof JobsRoute
  '/leads': typeof LeadsRoute
  '/quote': typeof QuoteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/follow-ups': typeof FollowUpsRoute
  '/jobs': typeof JobsRoute
  '/leads': typeof LeadsRoute
  '/quote': typeof QuoteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/follow-ups' | '/jobs' | '/leads' | '/quote'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/follow-ups' | '/jobs' | '/leads' | '/quote'
  id: '__root__' | '/' | '/follow-ups' | '/jobs' | '/leads' | '/quote'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FollowUpsRoute: typeof FollowUpsRoute
  JobsRoute: typeof JobsRoute
  LeadsRoute: typeof LeadsRoute
  QuoteRoute: typeof QuoteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follow-ups': {
      id: '/follow-ups'
      path: '/follow-ups'
      fullPath: '/follow-ups'
      preLoaderRoute: typeof FollowUpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FollowUpsRoute: FollowUpsRoute,
  JobsRoute: JobsRoute,
  LeadsRoute: LeadsRoute,
  QuoteRoute: QuoteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
